### ISSUE TITLE
infra: automated deployments

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#13]
Use github actions an run `yarn deploy` if build passes

**Comment by amilajack** [comment]
Looks like there's some existing solutions for this:
* https://github.com/peaceiris/actions-gh-pages
* https://github.com/JamesIves/github-pages-deploy-action
* https://github.com/crazy-max/ghaction-github-pages

**Comment by hamirmahal** [comment]
I saw something for this on [a tutorial on how to make a portfolio in React.js](https://www.freecodecamp.org/news/portfolio-app-using-react-618814e35843/).

I never looked into it because I wanted to learn how to do the deployments manually so I could really understand the process, but I can take a look into whether we can try the approach mentioned in the article if you think it's viable.

![image](https://user-images.githubusercontent.com/43425812/89950221-01582d00-dbde-11ea-959a-912266512cf3.png)

**Comment by amilajack** [comment]
So travis is actually somewhat of an outdated CI. Its probably going out of business because github actions is so much better. GH actions adds a lot of features that travis could never implement.

**Comment by hamirmahal** [comment]
I tried writing this out myself using the "Actions" tab under this repository.

This is what I came up with after modifying the template.

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run yarn deploy, which should build a deployable webpage, and then deploy it
      run: yarn deploy
```

This gave me an error, though.

![error: react-scripts: not found](https://user-images.githubusercontent.com/43425812/90087633-25953600-dcd2-11ea-909b-9dd7b634c0ea.png)
