### ISSUE TITLE
description container should have max height and allow overflow content to be scrollable 

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#160]
This should be done in tailwind. Here's the css just so you know how its done with without tailwind:

```css
.Description {
  max-height: 300px;
  overflow: scroll;
}
```
