### ISSUE TITLE
ui: redesign implementation: use custom font 

### ISSUE THREAD

**Issue by amilajack** [amilajack/freesound-player#35]
The current font is different from the one in the UI design, which is [Mplus 1p](https://fonts.google.com/specimen/M+PLUS+1p).

### 1. Add the `link` tags to the `head` tag:

![Screen Shot 2020-09-07 at 5 36 59 PM](https://user-images.githubusercontent.com/6374832/92422119-cc81bc00-f130-11ea-8e81-bea28710e008.png)

### 2. Import both fonts (extra bold and medium variants)

<img width="862" alt="Screen Shot 2020-09-17 at 10 36 49 PM" src="https://user-images.githubusercontent.com/6374832/93560192-708c1400-f936-11ea-9f86-0631b0444bb4.png">
<img width="922" alt="Screen Shot 2020-09-17 at 10 36 53 PM" src="https://user-images.githubusercontent.com/6374832/93560194-7124aa80-f936-11ea-97ac-4ca58e963e3f.png">

### 3. Enable the following styles:

```css
body {
  font-family: 'M PLUS 1p', sans-serif;
}

h1, h1, h3, h4, h5, h6 {
  font-weight: bold;
}
```
